# Generated by Django 4.1.6 on 2023-02-13 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music_Classification', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
